---
title: "GOCD2"
author: "Ruben Arslan"
date: "10/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE)
library(tidyverse)
```


```{r}
load("../gocd2/data/cleaned.rdata")
gocd2 <- diary %>% drop_na(`VPN-Zahl`)
lab_raw = readxl::read_xlsx("../gocd2/data/Datensatz_Zyklusstudie_Labor.xlsx") %>% drop_na(`VPN-Zahl`)

length(intersect(gocd2$`VPN-Zahl`, lab_raw$`VPN-Zahl`))
length(setdiff(gocd2$`VPN-Zahl`, lab_raw$`VPN-Zahl`))
length(setdiff(lab_raw$`VPN-Zahl`, gocd2$`VPN-Zahl`))
lab_only <- lab_raw %>% 
  # anti_join(gocd2, by= c("VPN-Zahl" = "VPN-Zahl")) %>% 
  mutate(
    `Date LH surge` = as.Date(if_else(`Date LH surge` == "xxx", NA_real_, as.numeric(`Date LH surge`)), origin = "1899-12-30")
  ) %>% 
  select(id = `VPN-Zahl`, 
         estradiol = `IBL_Estradiol pg/ml`,
         progesterone = `Progesterone pg/ml`, 
         estradiol_lcms = `Estradiol pg/ml`, 
         testosterone = `Testosterone pg/ml`,
         cortisol = `Cortisol nmol/l`,
         date = `Datum Lab Session`,
         date_lh = `Date LH surge`,
         date_mens = `Menstrual Onset`) %>% 
  mutate(bc_day = as.numeric(as.Date(date) - as.Date(date_mens)),
         bc_day = if_else(bc_day > -1, NA_real_, bc_day)) %>% 
  group_by(id) %>% 
  arrange(date_mens) %>% 
  mutate(cycle = as.numeric(factor(date_mens)))  %>% 
  group_by(id, cycle) %>% 
  mutate(date_lh = first(na.omit(date_lh)),
         lh_day = as.numeric(as.Date(date) - date_lh)
  ) %>% 
  ungroup() %>% 
  arrange(id, cycle, date)
qplot(lab_only$lh_day) + xlim(-30, NA)

lab_only %>% summarise(n(), n_distinct(id))
gocd2 %>% summarise(n(), n_distinct(session))

gocd2 <- gocd2 %>% select(id = `VPN-Zahl`, 
                          date = created_date,
                          bc_day = menstrual_onset_days_until, 
                          fc_day = menstrual_onset_days_since, 
                          cycle_length) %>% 
  as_tibble()

gocd2 <- lab_only %>% left_join(gocd2, by = c("id", "date"), suffix = c("", "_diary"))
relstatage <- lab_raw %>% mutate(partner = if_else(Relationship_status == 1, 0, 1)) %>%  select(id = `VPN-Zahl`, age = Age, partner) %>% distinct(id, .keep_all = TRUE)
gocd2 <- gocd2 %>% left_join(relstatage, by = c("id"))
gocd2 <- gocd2 %>% 
  # when we have a BC day from the online diary, we prefer it
  mutate(bc_day = coalesce(bc_day_diary, bc_day)) %>% 
  select(-bc_day_diary)

range(gocd2$fc_day, na.rm = T)
table(!is.na(gocd2$fc_day))
range(gocd2$bc_day, na.rm = T)
table(!is.na(gocd2$bc_day))
range(gocd2$lh_day, na.rm = T)
table(!is.na(gocd2$lh_day))

gocd2 <- gocd2 %>% 
  mutate(bc_day = if_else(is.na(cycle_length) & bc_day < -35, NA_real_, bc_day))
gocd2_u <- gocd2 %>% filter(is.na(cycle_length) | between(cycle_length, 25, 35))
range(gocd2_u$fc_day, na.rm = T)
table(!is.na(gocd2_u$fc_day))
range(gocd2_u$bc_day, na.rm = T)
table(!is.na(gocd2_u$bc_day))
range(gocd2_u$lh_day, na.rm = T)
table(!is.na(gocd2_u$lh_day))
qplot(gocd2_u$lh_day)

table( is.na(gocd2$progesterone), exclude = NULL)

min(gocd2$estradiol_lcms,na.rm=T)
qplot(gocd2$estradiol_lcms,na.rm=T) + scale_x_log10()
cor.test(gocd2$estradiol_lcms, gocd2$estradiol)

gocd2 <- gocd2 %>% 
  mutate(
    estradiol_cens = if_else(estradiol <= 2.1, "left", "none"),
    estradiol = if_else(estradiol_cens == "left", 2.1, estradiol),
    estradiol_lcms = if_else(!is.na(estradiol_lcms) | is.na(estradiol), estradiol_lcms, 1),
    estradiol_lcms_cens = if_else(estradiol_lcms <= 1, "left", "none")
  ) %>% 
  mutate(
    progesterone_cens = if_else(progesterone <= 0, "left", "none"),
    progesterone = if_else(progesterone_cens == "left", 0, progesterone)
  )
cor.test(gocd2$estradiol_lcms, gocd2$estradiol)

table(gocd2$estradiol_lcms_cens)

xtabs(~ is.na(progesterone) + is.na(estradiol), gocd2, exclude = NULL)

xtabs(~ estradiol_cens + is.na(estradiol), gocd2, exclude = NULL)

n_distinct(gocd2$id)
qplot(data = gocd2, estradiol, fill = estradiol_cens)

saveRDS(gocd2, "gocd2.rds")
```


### Correlation between E2 IA and LCMS
```{r}
gocd2 %>% select(estradiol, estradiol_lcms) %>% summarise_all(funs(mean = mean(., na.rm=T), sd = sd(., na.rm=T), logmean = mean(log(.), na.rm=T), logsd = sd(log(.), na.rm=T))) %>% knitr::kable()
ggplot(gocd2, aes(estradiol, estradiol_lcms)) + geom_point() + geom_abline(slope = 1, intercept = 0) + coord_equal(xlim = c(0,45), ylim = c(0,45))
cor.test(gocd2$estradiol, gocd2$estradiol_lcms)
cor.test(log(gocd2$estradiol), log(gocd2$estradiol_lcms))
ggplot(gocd2, aes(estradiol, estradiol_lcms)) + scale_x_log10() + scale_y_log10() + geom_point()
```

## Summarize
```{r}
source("0_summary_functions.R")
```

```{r}
df <- gocd2 %>% select(id, cycle, bc_day, fc_day, lh_day, hormone = progesterone, hormone_cens = progesterone_cens, cycle_length, age, partner)

summarise_hormone(df = df, Dataset = "GOCD2", Hormone = "Progesterone", Method = "Salivary liquid chromatography–mass spectrometry",
                  Citation = "Jünger, J., Kordsmeyer, T. L., Gerlach, T. M., & Penke, L. (2018). Fertile women evaluate male bodies as more attractive, regardless of masculinity. Evolution and Human Behavior: Official Journal of the Human Behavior and Evolution Society, 39(4), 412–423. https://doi.org/10.1016/j.evolhumbehav.2018.03.007",
                  LOQ = 5,
                  CV_intra = 10.8,
                  CV_inter = 9.7,
                  Procedure = "Next, the saliva samples were collected via passive drool. For hormone assays, we collected four saliva samples from each participant (one per testing session). Contamination of saliva samples was minimized by asking participants to abstain from eating, drinking (except plain water), smoking, chewing gum or brushing teeth for at least one hour before each session. The samples were stored at -80°C directly after collection until shipment on dry ice to the Kirschbaum Lab at Technical University of Dresden, Germany, where estradiol, progesterone, testosterone and cortisol was assessed via liquid chromatography mass spectrometry (LCMS; Gao, Stalder, & Kirschbaum, 2015). Since the LCMS analysis of the estradiol levels did only detect 22% of all possible values, the samples were reanalyzed using the highly sensitive 17β-estradiol enzyme immunoassay kit (IBL International, Hamburg, Germany). These latter estradiol values were used in subsequent analyses. ",
                  Scheduling = "Peri-ovulatory & Luteal 'Sessions two to five, the computer-based testing sessions, took place across two ovulatory cycles per participant, once per cycle during the fertile and once during the luteal phase. To control for possible effects of diurnal changes in hormone levels (Bao et al., 2003; Veldhuis et al., 1988), all sessions took place in the second half of the day (mainly between 11.30 am and 6 pm).'", 
                  LH_test = "highly sensitive (10 mIU/ml) urine ovulation test strips from purbay®, which measure the luteinizing hormone (LH). These LH-tests had to be done at home at the estimated day of ovulation and the four days prior to that and results were self- reported by the participants.")

df <- gocd2%>% select(id, cycle, bc_day, fc_day, lh_day, hormone = estradiol, hormone_cens = estradiol_cens, cycle_length, age, partner)

summarise_hormone(df = df, Dataset = "GOCD2", 
                  Hormone = "Estradiol",
                  Method = "Salivary immunoassay (IBL)",
                  Citation = "Jünger, J., Kordsmeyer, T. L., Gerlach, T. M., & Penke, L. (2018). Fertile women evaluate male bodies as more attractive, regardless of masculinity. Evolution and Human Behavior: Official Journal of the Human Behavior and Evolution Society, 39(4), 412–423. https://doi.org/10.1016/j.evolhumbehav.2018.03.007",
                  LOD = 2.1,
                  LOQ = 2.1,
                  CV_intra = 8.8,
                  CV_inter = 11.3,
                  Procedure = "Next, the saliva samples were collected via passive drool. For hormone assays, we collected four saliva samples from each participant (one per testing session). Contamination of saliva samples was minimized by asking participants to abstain from eating, drinking (except plain water), smoking, chewing gum or brushing teeth for at least one hour before each session. The samples were stored at -80°C directly after collection until shipment on dry ice to the Kirschbaum Lab at Technical University of Dresden, Germany, where estradiol, progesterone, testosterone and cortisol was assessed via liquid chromatography mass spectrometry (LCMS; Gao, Stalder, & Kirschbaum, 2015). Since the LCMS analysis of the estradiol levels did only detect 22% of all possible values, the samples were reanalyzed using the highly sensitive 17β-estradiol enzyme immunoassay kit (IBL International, Hamburg, Germany). These latter estradiol values were used in subsequent analyses. ",
                  Scheduling = "Peri-ovulatory & Luteal 'Sessions two to five, the computer-based testing sessions, took place across two ovulatory cycles per participant, once per cycle during the fertile and once during the luteal phase. To control for possible effects of diurnal changes in hormone levels (Bao et al., 2003; Veldhuis et al., 1988), all sessions took place in the second half of the day (mainly between 11.30 am and 6 pm).'", 
                  LH_test = "highly sensitive (10 mIU/ml) urine ovulation test strips from purbay®, which measure the luteinizing hormone (LH). These LH-tests had to be done at home at the estimated day of ovulation and the four days prior to that and results were self- reported by the participants.")

df <- gocd2 %>% select(id, cycle, bc_day, fc_day, lh_day, hormone = estradiol_lcms, hormone_cens = estradiol_lcms_cens, cycle_length, age, partner)

summarise_hormone(df = df, 
                  Dataset = "GOCD2", 
                  Hormone = "Estradiol LCMS", 
                  Method = "Salivary liquid chromatography–mass spectrometry",
                  Citation = "Jünger, J., Kordsmeyer, T. L., Gerlach, T. M., & Penke, L. (2018). Fertile women evaluate male bodies as more attractive, regardless of masculinity. Evolution and Human Behavior: Official Journal of the Human Behavior and Evolution Society, 39(4), 412–423. https://doi.org/10.1016/j.evolhumbehav.2018.03.007",
                  LOD = NA,
                  LOQ = 1,
                  CV_intra = "4.7-8.3% (10ng/ml to 0.01ng/ml)",
                  CV_inter = "4.3-9.1% (10ng/ml to 0.01ng/ml)",
                  Procedure = "Next, the saliva samples were collected via passive drool. For hormone assays, we collected four saliva samples from each participant (one per testing session). Contamination of saliva samples was minimized by asking participants to abstain from eating, drinking (except plain water), smoking, chewing gum or brushing teeth for at least one hour before each session. The samples were stored at -80°C directly after collection until shipment on dry ice to the Kirschbaum Lab at Technical University of Dresden, Germany, where estradiol, progesterone, testosterone and cortisol was assessed via liquid chromatography mass spectrometry (LCMS; Gao, Stalder, & Kirschbaum, 2015). Since the LCMS analysis of the estradiol levels did only detect 22% of all possible values, the samples were reanalyzed using the highly sensitive 17β-estradiol enzyme immunoassay kit (IBL International, Hamburg, Germany). These latter estradiol values were used in subsequent analyses. ",
                  Scheduling = "Peri-ovulatory & Luteal 'Sessions two to five, the computer-based testing sessions, took place across two ovulatory cycles per participant, once per cycle during the fertile and once during the luteal phase. To control for possible effects of diurnal changes in hormone levels (Bao et al., 2003; Veldhuis et al., 1988), all sessions took place in the second half of the day (mainly between 11.30 am and 6 pm).'", 
                  LH_test = "highly sensitive (10 mIU/ml) urine ovulation test strips from purbay®, which measure the luteinizing hormone (LH). These LH-tests had to be done at home at the estimated day of ovulation and the four days prior to that and results were self- reported by the participants.")

df <- gocd2 %>% select(id, cycle, bc_day, fc_day, lh_day, estradiol, progesterone, cycle_length)

summarise_hormones(df = df, Dataset = "GOCD2")
```

